name: artifacts test workflow 

on:
  workflow_dispatch:
    
  # push:
  #   branches:
  #       - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: create directory name downloads
        run: mkdir downloads
        
      - name: cd to downloads and making txt files 
        run: |
          cd downloads
          echo 'dx0'    > daksh_0.txt
          echo 'dx1'    > daksh_1.txt
          echo 'dx2'  > daksh_2.txt
          cd ..
    
      - name: Upload Artifact GitHub Action
        uses: actions/upload-artifact@v3
        with: 
          name: testartifacts
          path: downloads

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # - name: Download artifacts

      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: testartifacts
          path: downloads
    
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: downloads
