name: zip test 2  workflow

on:
  workflow_dispatch:
    
  # push:
  #   branches:
  #       - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use node js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # - name: create directory name downloads
        # run: mkdir downloads
        
      - name: cd to downloads and install-build npm
        run: |
          npm install
          npm run build
        env: 
          CI: true 

      - name: Display structure of downloaded files
        run: ls -a

      - name: find the present working directiory path
        run: |
          pwd_var=$(pwd)
          echo "The present working directory is: $pwd_var"


        # working-directory: download

      - name: making a zip file of .next folder
        run: |
          
          zip -r next.zip .next
          cd .. 

  #     - name: Upload Artifact GitHub Action
  #       uses: actions/upload-artifact@v2
  #       with: 
  #         name: testartifacts
  #         path: /home/runner/work/nextdeploy0/nextdeploy0

  # release:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     # - name: Download artifacts

  #     - uses: actions/checkout@v3

  #     - name: give permission to all folder and subfolders
  #       run: |
  #         chmod -R 777 /home 

  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: testartifacts
  #         path: /home/runner/work/nextdeploy0/nextdeploy0
    

